return {}
-- return {
--     "mfussenegger/nvim-lint",
--     opts = {
--         -- Event to trigger linters
--         events = { "BufWritePost", "BufReadPost", "InsertLeave" },
--         linters_by_ft = {
--             fish = { "fish" },
--             go = { "golangcilint" },
--             -- Use the "*" filetype to run linters on all filetypes.
--             -- ['*'] = { 'global linter' },
--             -- Use the "_" filetype to run linters on filetypes that don't have other linters configured.
--             -- ['_'] = { 'fallback linter' },
--             -- ["*"] = { "typos" },
--         },
--         -- LazyVim extension to easily override linter options
--         -- or add custom linters.
--         ---@type table<string,table>
--         linters = {
--             -- Configure golangci-lint
--             golangcilint = {
--                 name = "golangci-lint",
--                 cmd = "golangci-lint",
--                 stdin = false,
--                 args = {
--                     "run",
--                     "--out-format=json",
--                     "--path-prefix=" .. vim.fn.getcwd(),
--                 },
--                 stream = "stdout",
--                 ignore_exitcode = true,
--                 parser = function(output, bufnr)
--                     local diagnostics = {}
--                     local decode_ok, decoded = pcall(vim.json.decode, output)
--
--                     if not decode_ok or not decoded or not decoded.Issues then
--                         return diagnostics
--                     end
--
--                     for _, issue in ipairs(decoded.Issues) do
--                         local filename = issue.Pos.Filename
--                         local current_file = vim.api.nvim_buf_get_name(bufnr)
--
--                         -- Only show diagnostics for the current file
--                         if vim.fn.fnamemodify(filename, ":p") == current_file then
--                             table.insert(diagnostics, {
--                                 lnum = (issue.Pos.Line or 1) - 1,
--                                 col = (issue.Pos.Column or 1) - 1,
--                                 end_lnum = (issue.Pos.Line or 1) - 1,
--                                 end_col = (issue.Pos.Column or 1) - 1,
--                                 severity = vim.diagnostic.severity.WARN,
--                                 message = issue.Text,
--                                 source = "golangci-lint",
--                                 code = issue.FromLinter,
--                             })
--                         end
--                     end
--
--                     return diagnostics
--                 end,
--                 -- Optional: Only enable when golangci-lint config is present
--                 condition = function(ctx)
--                     return vim.fs.find({
--                         ".golangci.yml",
--                         ".golangci.yaml",
--                         ".golangci.toml",
--                         ".golangci.json",
--                     }, { path = ctx.filename, upward = true })[1] ~= nil
--                     -- Remove the condition above if you want it to always run with default config
--                 end,
--             },
--             -- -- Example of using selene only when a selene.toml file is present
--             -- selene = {
--             --   -- `condition` is another LazyVim extension that allows you to
--             --   -- dynamically enable/disable linters based on the context.
--             --   condition = function(ctx)
--             --     return vim.fs.find({ "selene.toml" }, { path = ctx.filename, upward = true })[1]
--             --   end,
--             -- },
--         },
--     },
-- }
