return {}
-- return {
--     "nvim-telescope/telescope.nvim",
--     enabled = true,
--     opts = {
--         defaults = {
--             prompt_prefix = "> ",
--             selection_caret = "-> ",
--             path_display = { "smart" },
--             dynamic_preview_title = true,
-- 
--             winblend = 10,
--             sorting_strategy = "ascending",
--             layout_strategy = "vertical",
--             layout_config = {
--                 vertical = {
--                     prompt_position = "bottom",
--                     height = 0.95,
--                     width = 0.8,
--                 },
--             },
--         },
--         pickers = {
--             find_files = {
--                 hidden = true,
--             },
--         },
--     },
-- }
